blank_issues_enabled: true
contact_links:
    - name: 📃 Documentation Issue
      url: https://github.com/Emmanuelmichaelmaro/mzawadie-storefront/discussions/categories/documentation
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: 🤔 Questions and Help
      url: https://github.com/Emmanuelmichaelmaro/mzawadie-storefront/discussions/categories/q-a
      about: This issue tracker is for support questions and suggest new features here.